export { default as Home } from './HomePage'
export { default as ItemDetail } from '../components/ItemDetail/index'
export { default as Checkout } from './CheckOut'
export { default as Barato } from './Barato'
export { default as Intermedio } from './Intermedio'